language: node_js
node_js:
  - 10
cache: npm
install: npm ci
script:
  - npm run build:prod
deploy:
  provider: firebase
  skip_cleanup: true
  token: 
    secure: '${firebase_token}'
  on:
    branch: develop
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
